### ISSUE TITLE
Add repo & env var  inputs to kubevirt-talos template 

### ISSUE THREAD

**Issue by hh** [cncf-infra/coder-templates#12]
When creating a new instance in pair we can provide repositories and environment vars.
- https://pair.sharing.io/instances/new

This should allow us to expose more features from our pair image to the coder workspace cluster/pod.

**Comment by BobyMCbobs** [comment]
To clarify, is this referring to the automated cloning of repositories upon instance creation?

**Comment by hh** [comment]
Yes, and the env vars we set in the environment pod.

**Comment by hh** [comment]
In pair webui at https://pair.sharing.io/instances/new we can input a list of repos:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/31331/207916383-7cd9a214-cc40-439e-ad29-54e885f5e13f.png">

This gets populated to the environment StatefulSet in [.sharing.io](https://github.com/sharingio/.sharing.io/tree/37cea025210cfaeeeaaef41adf6fc755999b6498)/[cluster-api](https://github.com/sharingio/.sharing.io/tree/37cea025210cfaeeeaaef41adf6fc755999b6498/cluster-api)/[manifests](https://github.com/sharingio/.sharing.io/tree/37cea025210cfaeeeaaef41adf6fc755999b6498/cluster-api/manifests)/[environment.yaml](https://github.com/sharingio/.sharing.io/blob/37cea025210cfaeeeaaef41adf6fc755999b6498/cluster-api/manifests/environment.yaml#L55-L56)

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: environment
spec:
  template:
    spec:
      containers:
        - command:
            - pair-init.sh
          env:
            - name: INIT_DEFAULT_REPOS
              value: "${SHARINGIO_PAIR_INSTANCE_SETUP_REPOS}"
```

INIT_DEFAULT_REPOS is used by the environment pod via [pair-init.sh](https://github.com/sharingio/environment/blob/master/usr/local/bin/pair-init.sh#L59-L73) to check out the repos.

```
# Clone all projects
(
    if [ -n "$INIT_DEFAULT_REPOS" ]; then
        mkdir -p "${INIT_DEFAULT_REPOS_FOLDER}"
        for repo in ${INIT_DEFAULT_REPOS}; do
            if [ "$PROJECT_CLONE_STRUCTURE" = "structured" ]; then
                git-clone-structured "$repo" || true
            elif [ "$PROJECT_CLONE_STRUCTURE" = "plain" ]; then
                git clone -v --recursive "$repo" || true
            fi
        done
    fi
    cd
    eval "$INIT_PREFINISH_BLOCK"
)
```

Please add a [coder_parameter](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter) to the kubevirt-talos template allowing *INIT_DEFAULT_REPOS* to be set during creation.

**Comment by hh** [comment]
In pair webui at https://pair.sharing.io/instances/new we can input a list of environment vars:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/31331/207918632-34411c99-cc0a-4672-99de-bfddc49b75e1.png">

This form is created by [https://github.com/sharingio/pair/blob/aab8af9f0447e1b0725f9f348a8abb4f1467cb24/apps/client/src/client/views.clj#L164-L167](pair/apps/client/src/client/view.clj):

```
   [:div.form-group
    [:label {:form "envvars"} "Environment Variables"]
    [:textarea {:name "envvars"
                :id "envvars"
                :placeholder "PAIR=sharing\nSHARE=pairing"}]
    [:p.helper "Add env vars as KEY=value, with each new variable on its own line."]]
```

Processed by [packet.clj#text->env-map]( https://github.com/sharingio/pair/blob/72cac761ba515e3564b6aa84bc2b635da2e025e8/apps/client/src/client/packet.clj#L21-L26) which is called by [launch()](https://github.com/sharingio/pair/blob/72cac761ba515e3564b6aa84bc2b635da2e025e8/apps/client/src/client/packet.clj#L107) when creating an instance spec as *:env*:

```
        instance-spec {:type type
                       :facility facility
                       :name name
                       :kubernetesNodeCount (Integer. (or kubernetesNodeCount 0))
                       :setup {:user username
                               :guests (if (empty? guests)
                                         [ ]
                                         (clojure.string/split guests #" "))
                               :githubOAuthToken (if (empty? noGitHubToken) "" token)
                               :env (if (empty? envvars) [] (text->env-map envvars))
                               :timezone timezone
                               :repos (if (empty? repos)
                                        [ ]
                                        (clojure.string/split repos #" "))
                               :fullname fullname
                               :email email
                               :extraEmails emails}}
```

Currently this may get written to `/root/.sharing-io-pair-init.env`
via [KubernetesTemplateResources()](https://github.com/sharingio/pair/blob/fdc243649284060cbd881adbd9867f2327f2394f/apps/cluster-api-manager/instances/kubernetes.go#L708-L733)

However it's fine to just add these directly to the environment Stateful itself similar to the * INIT_DEFAULT_REPOS* above.

**Comment by hh** [comment]
We should be able to process the new `coder_parameters` into a [terraform templated](https://developer.hashicorp.com/terraform/language/functions/templatefile) version of the environment StatefulSet.

**Comment by BobyMCbobs** [comment]
check out #14

**Comment by hh** [comment]
We should loop back to ENV vars as well: https://github.com/cncf-infra/coder-templates/issues/12#issuecomment-1353419275

It'll be very similar.

**Comment by BobyMCbobs** [comment]
> We should loop back to ENV vars as well: [#12 (comment)](https://github.com/cncf-infra/coder-templates/issues/12#issuecomment-1353419275)
> 
> It'll be very similar.

@hh, it is unclear to me why the two topics are grouped together.

The way that Pair has performed the templating in the past (through bash variables) is simply not possible with the way that Terraform works. I am currently unsure how the dynamic assigning of environment various could be done

**Comment by hh** [comment]
Both options need us to set env vars for the pod.
It's templating within terraform. Here is a working example:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: environment
spec:
  template:
    spec:
      containers:
        - command:
            - pair-init.sh
          env:
            %{for v in split(" ",env_vars)}
            - name: "${split("=",v)[0]}"
              value: "${split("=",v)[1]}"%{ endfor}
```

```
echo 'templatefile("${path.module}/env_t.yaml", { env_vars = "FOO=bar BAZ=boo"})' | terraform console
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: environment
spec:
  template:
    spec:
      containers:
        - command:
            - pair-init.sh
          env:
            
            - name: "FOO"
              value: "bar"
            - name: "BAZ"
              value: "boo"
```
